console.log(`${boo1} [${typeof boo1}]`);
console.log(`${boo2} [${typeof boo2}]`);
console.log(`${nb1} [${typeof nb1}]`);
console.log(`${nb2} [${typeof nb2}]`);
console.log(`${bit1} [${typeof bit1}]`);
console.log(`${bit2} [${typeof bit2}]`);
console.log(`${str1} [${typeof str1}]`);
console.log(`${str2} [${typeof str2}]`);
console.log(`${u1} [${typeof u1}]`);